spring:
  application:
    name: amsensors
  profiles:
    active: dev
  config:
    import:
      optional:configserver:http://localhost:8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
